production:
  <<: *ALL
  database: subway_production

test: &ALL
  <<: *ALL
  database: subway_test

cucumber:
  <<: *ALL
  database: subway_test

development: &ALL
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: subway_development
  username: root
  password:
  host: localhost

